# Generated by Django 4.2.29 on 2026-03-15 17:55

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_options_category_parent_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Write your article with images, etc.'),
        ),
    ]
