# Generated by Django 4.2.29 on 2026-03-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blogpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Publication categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(blank=True, help_text='List authors as they appear', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('link', models.URLField(blank=True, help_text='URL to external resource')),
                ('file', models.FileField(blank=True, help_text='Upload PDF or document', null=True, upload_to='publications/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.publicationcategory')),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
    ]
