# Generated by Django 4.2.29 on 2026-05-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bookmark_tutorialprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
